% Author: Laercio Barbosa 
% e-mail: leoabubauru@hotmail.com
% Github: https://github.com/laercio-barbosa/rmaProject
% Date: 31/05/2017
% 
% SLAM frontend for V-REP .
%
% Based on: mapMakerGUI from Jai Juneja (See Copyright info bellow)
%    - http://www.jaijuneja.com/blog/2013/05/simultaneous-localisation-mapping-matlab/
%    - https://github.com/jaijuneja/ekf-slam-matlab
%
% COPYRIGHT INFO FROM mapMakerGUI
% ===============================
% 
% This software was written and developed by Jai Juneja as part of an 
% undergraduate project in the Department of Engineering Science, University of 
% Oxford. If you have any questions, I can be contacted at: 
% jai.juneja@balliol.ox.ac.uk or jai.juneja@gmail.com
% 
% Please feel free to use, modify and distribute the software for personal or 
% research purposes, along with acknowledgement of the author and inclusion of
% this copyright information.
% 
% Some of the code included has been adapted from other software. They are 
% acknowledged as follows:
% 
% Code for Jacobian transformations was adapted from a SLAM course by Joan Sola 
% (http://www.joansola.eu/JoanSola/eng/course.html)
% ICP algorithm in doICP.m was adapted from code written by Ajmal Saeed Mian 
% (relevant copyright informtion included in the file).
% Any 3rd party code that has been untouched is in the folder 3rd-party
function Graphics = initGraphics(World, handles)

    Graphics.Map = line('parent',handles.mainAxes,...
        'linestyle','none',...
        'marker','s',...
        'MarkerFaceColor', 'y', ...
        'color','y',...
        'xdata',[],...
        'ydata',[]);
    
    Graphics.World = line('parent',handles.mainAxes,...
        'linestyle','none',...
        'marker','o',...
        'color','b',...
        'xdata',World.W(1,:),...
        'ydata',World.W(2,:));

    Graphics.TrueRob = line('parent',handles.mainAxes,...
        'color','b',...
        'xdata',[],...
        'ydata',[]);
    
    Graphics.Rob = line('parent',handles.mainAxes,...
        'color','r',...
        'xdata',[],...
        'ydata',[]);

    Graphics.Lmk = line('parent',handles.mainAxes,...
        'linestyle','none',...
        'marker','+',...
        'color','g',...
        'xdata',[],...
        'ydata',[]);

    Graphics.LmkLines = line(...
        'parent',handles.mainAxes, ...
        'color','g', ...
        'xdata',[], ...
        'ydata',[]);

    Graphics.Ellipse = zeros(1,size(World.W,2));
    for i = 1:numel(Graphics.Ellipse)
        Graphics.Ellipse(i) = line(...
            'parent', handles.mainAxes,...
            'color','r',...
            'xdata',[],...
            'ydata',[]);
    end

    Graphics.RobCov = line(...
        'parent', handles.mainAxes,...
        'color','r',...
        'xdata',[],...
        'ydata',[]);
    
    Graphics.Scan = line('parent',handles.mainAxes,...
        'linestyle','none',...
        'marker','x',...
        'color','r',...
        'xdata',[],...
        'ydata',[]);
    
    Graphics.R_hist = line('xdata', [], ...
        'ydata', [], ...
        'color', 'b', ...
        'parent', handles.mainAxes);

    Graphics.r_hist = line('xdata', [], ...
        'ydata', [], ...
        'color', 'r', ...
        'parent', handles.mainAxes);
    
    Graphics.map1 = imagesc([], ...
        'parent', handles.map1);
    colormap(gray);
    axis equal
end